{
 "title": "Stellar Core Monitoring",
 "tags": [ "stellar-core" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": "label_values(stellar_core_started_on, environment)"
   },
   {
    "name": "instance",
    "query": "label_values(stellar_core_started_on{environment=~\"$environment\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Critical metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Monitored node reachability",
   "type": "table",
   "description": "List of nodes matching currently selected filters.\n\nIf no nodes are showing make sure stellar-core nodes are scraped by prometheus by a job matching reges \".*stellar.core.*\"",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "up{job=~\".*stellar.core.*\", environment=~\"$environment\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Quorum intersection",
   "type": "table",
   "description": "Quorum intersection",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "stellar_core_quorum_transitive_intersection{environment=~\"$environment\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Quorum Transitive Critical Peers Details",
   "type": "table",
   "description": "Quorum Transitive Critical Peers\nPer-instance details",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "stellar_core_quorum_transitive_critical{environment=~\"$environment\",instance=~\"$instance\"} == 1",
     "legendFormat": "{{instance}} - {{peer}}"
    }
   ]
  },
  {
   "title": "Ledger age",
   "type": "graph",
   "description": "Ledger age. 10s is considered critical and 8s warning",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "stellar_core_ledger_age{environment=~\"$environment\",instance=~\"$instance\"} ",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg(avg_over_time(stellar_core_ledger_age{environment=~\"$environment\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "Average (5min rolling)"
    }
   ]
  },
  {
   "title": "% of nodes with ledgers over 10s old",
   "type": "graph",
   "description": "Percentage of nodes with ledgers over 10s old.\nValues greater than 35% are considered critical",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n  count(stellar_core_ledger_age{environment=~\"$environment\",instance=~\"$instance\"} > 10) /\n  count(stellar_core_ledger_age{environment=~\"$environment\",instance=~\"$instance\"}) * 100\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Quorum fail at",
   "type": "table",
   "description": "Quorum fail at. Value of 1 means we'll fail if one of the peers fails.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "stellar_core_quorum_fail_at{environment=~\"$environment\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "% of nodes at risk of quorum loss",
   "type": "graph",
   "description": "Percentage of nodes that have quorum fail_at of 1 or less.\nValues greater than 35% are considered critical",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n  count(stellar_core_quorum_fail_at{environment=~\"$environment\",instance=~\"$instance\"} <= 1) /\n  count(stellar_core_quorum_fail_at{environment=~\"$environment\",instance=~\"$instance\"}) * 100\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Node sync status",
   "type": "table",
   "description": "Node sync status",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "stellar_core_synced{environment=~\"$environment\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "% of nodes nodes out of sync",
   "type": "graph",
   "description": "Percentage of nodes which are out of sync.\nValues greater than 35% are considered critical",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n  count(stellar_core_synced{environment=~\"$environment\",instance=~\"$instance\"} == 0) /\n  count(stellar_core_synced{environment=~\"$environment\",instance=~\"$instance\"}) * 100\n) or vector(0)"
    }
   ]
  },
  {
   "title": "Quorum",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Quorum missing peers",
     "type": "table",
     "description": "Nodes with missing quorum peers",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "stellar_core_quorum_missing{environment=~\"$environment\",instance=~\"$instance\"} > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Quorum delayed peers",
     "type": "table",
     "description": "Nodes with delayed quorum peers",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "stellar_core_quorum_delayed{environment=~\"$environment\",instance=~\"$instance\"} > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Quorum transitive changes (5min window)",
     "type": "graph",
     "description": "Quorum transitive changes in 5min window. Frequent changes might indicate flaky nodes in the quorumset",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "changes(stellar_core_quorum_transitive_last_check_ledger{environment=~\"$environment\", instance=~\"$instance\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Buckets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bucket Batch Addtime",
     "type": "graph",
     "description": "Bucket Batch Addtime",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "stellar_core_bucket_batch_addtime_seconds{environment=~\"$environment\", instance=~\"$instance\",quantile=\"0.75\"}",
       "legendFormat": "P75 {{instance}}"
      },
      {
       "expr": "stellar_core_bucket_batch_addtime_seconds{environment=~\"$environment\", instance=~\"$instance\",quantile=\"0.99\"}",
       "legendFormat": "P99 {{instance}}"
      },
      {
       "expr": "avg(\n  irate(stellar_core_bucket_batch_addtime_seconds_sum{environment=~\"$environment\", instance=~\"$instance\"}[1m])\n  / irate(stellar_core_bucket_batch_addtime_seconds_count{environment=~\"$environment\", instance=~\"$instance\"}[1m])\n)",
       "legendFormat": "Average"
      }
     ]
    },
    {
     "title": "Bucket Memory Shared",
     "type": "graph",
     "description": "Bucket Memory Shared",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "Objects #" }
     ],
     "targets": [
      {
       "expr": "avg(stellar_core_bucket_memory_shared{environment=~\"$environment\", instance=~\"$instance\"})",
       "legendFormat": "Average"
      },
      {
       "expr": "stellar_core_bucket_memory_shared{environment=~\"$environment\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Bucket Batch Objects Added",
     "type": "graph",
     "description": "Bucket Batch Objects Added",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "Objects #" }
     ],
     "targets": [
      {
       "expr": "avg(rate(stellar_core_bucket_batch_objectsadded{environment=~\"$environment\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "Average"
      },
      {
       "expr": "rate(stellar_core_bucket_batch_objectsadded{environment=~\"$environment\", instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Overlay",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overlay Timeout Idle",
     "type": "graph",
     "description": "Overlay Timeout Idle",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "avg(rate(stellar_core_overlay_timeout_idle{environment=~\"$environment\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "Average"
      },
      {
       "expr": "rate(stellar_core_overlay_timeout_idle{environment=~\"$environment\", instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Overlay Timeout Staggler",
     "type": "graph",
     "description": "Overlay Timeout Straggler",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "avg(rate(stellar_core_overlay_timeout_straggler{environment=~\"$environment\", instance=~\"$instance\"}[1m]))",
       "legendFormat": "Average"
      },
      {
       "expr": "rate(stellar_core_overlay_timeout_straggler{environment=~\"$environment\", instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Overlay Connection Pending",
     "type": "graph",
     "description": "Overlay Connection Pending",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "avg(stellar_core_overlay_connection_pending{environment=~\"$environment\", instance=~\"$instance\"})",
       "legendFormat": "Average"
      },
      {
       "expr": "stellar_core_overlay_connection_pending{environment=~\"$environment\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Overlay Connection Authenticated",
     "type": "graph",
     "description": "Overlay Connection Authenticated",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "avg(stellar_core_overlay_connection_authenticated{environment=~\"$environment\", instance=~\"$instance\"})",
       "legendFormat": "Average"
      },
      {
       "expr": "stellar_core_overlay_connection_authenticated{environment=~\"$environment\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "App",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "App Post On Main Thread Delay",
     "type": "graph",
     "description": "App Post On Main Thread Delay",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(\n  irate(stellar_core_app_post_on_main_thread_delay_seconds_sum{environment=~\"$environment\", instance=~\"$instance\"}[1m])\n  / irate(stellar_core_app_post_on_main_thread_delay_seconds_count{environment=~\"$environment\", instance=~\"$instance\"}[1m])\n)",
       "legendFormat": "Average"
      },
      {
       "expr": "stellar_core_app_post_on_main_thread_delay_seconds{environment=~\"$environment\", instance=~\"$instance\",quantile=\"0.75\"}",
       "legendFormat": "P75 {{instance}}"
      },
      {
       "expr": "stellar_core_app_post_on_main_thread_delay_seconds{environment=~\"$environment\", instance=~\"$instance\",quantile=\"0.99\"}",
       "legendFormat": "P99 {{instance}}"
      }
     ]
    },
    {
     "title": "App Post On Background Thread Delay",
     "type": "graph",
     "description": "App Post On Background Thread Delay",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(\n  irate(stellar_core_app_post_on_background_thread_delay_seconds_sum{environment=~\"$environment\", instance=~\"$instance\"}[1m])\n  / irate(stellar_core_app_post_on_background_thread_delay_seconds_count{environment=~\"$environment\", instance=~\"$instance\"}[1m])\n)",
       "legendFormat": "Average"
      },
      {
       "expr": "stellar_core_app_post_on_background_thread_delay_seconds{environment=~\"$environment\", instance=~\"$instance\",quantile=\"0.75\"}",
       "legendFormat": "P75 {{instance}}"
      },
      {
       "expr": "stellar_core_app_post_on_background_thread_delay_seconds{environment=~\"$environment\", instance=~\"$instance\",quantile=\"0.99\"}",
       "legendFormat": "P99 {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Crypto",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Crypto Verify Hit Rate",
     "type": "graph",
     "description": "Crypto Verify Hit Rate",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "irate(stellar_core_crypto_verify_hit{environment=~\"$environment\",instance=~\"$instance\"}[1m])\n/ irate(stellar_core_crypto_verify_total{environment=~\"$environment\",instance=~\"$instance\"}[1m])\n* 100",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "avg(\n  irate(stellar_core_crypto_verify_hit{environment=~\"$environment\",instance=~\"$instance\"}[1m])\n  / irate(stellar_core_crypto_verify_total{environment=~\"$environment\",instance=~\"$instance\"}[1m])\n  * 100\n)",
       "legendFormat": "Average"
      }
     ]
    }
   ]
  }
 ]
}